### ISSUE TITLE
Tool Cannot Parse HFS File

### ISSUE THREAD

**Issue by Dogboy31** [healingbrew/HFSExtract#2]
`Unhandled Exception: HFSExtract.HFSException: Can't parse HFS File
   at HFSExtract.HFSFile..ctor(BinaryReader reader, Boolean slim) in H:\Datamining\Vindictus\HFSExtract\HFSExtract\HFSFile.cs:line 31
   at HFSExtract.HFS.Initialize(Stream stream) in H:\Datamining\Vindictus\HFSExtract\HFSExtract\HFS.cs:line 43
   at HFSExtract.HFS..ctor(String path) in H:\Datamining\Vindictus\HFSExtract\HFSExtract\HFS.cs:line 20
   at HFSExtract.CLI.Program.Main(String[] args) in H:\Datamining\Vindictus\HFSExtract\HFSExtract.CLI\Program.cs:line 21`

Vindictus has just recently updated with the release of Lethor. When using this tool, this error above came up. When will we expect an ETA for this fix?

Thanks!

**Comment by neptuwunium** [comment]
Vindictus updated with a new, encrypted archive format. No ETA on when, if ever I'll fix this.

**Comment by neptuwunium** [comment]
Updated: https://github.com/yretenai/HFSExtract/releases/tag/0.2.0
