### ISSUE TITLE
Thank you very much for your tools

### ISSUE THREAD

**Issue by a987156759** [healingbrew/HFSExtract#8]
Thank God, I can unpack the model, but how can I unpack the model? Unpack HFS and then package HSF

**Comment by CrossV4** [comment]
hey i can't unpack, can you help me pls ??

HFSExtract.CLI.exe "C:\Program Files (x86)\Steam\steamapps\common\Vindictus\en-US\Base_hl2.hfs" "C:\Users\e--b\extract\"

here is my code also i tried like this: HFSExtract.CLI.exe C:/Program Files (x86)/Steam/steamapps/common/Vindictus/en-US/Base_hl2.hfs C:/Users/e--b/text/  but not either working..

Unhandled exception. System.IO.IOException: Parametre hatalı. : 'C:\Program Files (x86)\Steam\steamapps\common\Vindictus\en-US\Base_hl2.hfs'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry() in System.Private.CoreLib.dll:token 0x6006379+0x1c
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext() in System.Private.CoreLib.dll:token 0x6006378+0x32
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in System.Private.CoreLib.dll:token 0x6006d78+0x71
   at HFSExtract.CLI.Program.Main(String[] args) in G:\Datamining\Vindictus\HFSExtract2\HFSExtract.CLI\Program.cs:line 16


can you help me to how to i unpack it ?

**Comment by ValiaP** [comment]
> 

Same issue

**Comment by ValiaP** [comment]
Oh, you need to use folder path, remove the file name.

**Comment by ValiaP** [comment]
Bug I get new errors:
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at HFSExtract.HFSArchive..ctor(Stream stream, String fileName) in G:\Datamining\Vindictus\HFSExtract2\HFSExtract\HFSArchive.cs:line 53
   at HFSExtract.CLI.Program.Main(String[] args) in G:\Datamining\Vindictus\HFSExtract2\HFSExtract.CLI\Program.cs:line 17
