### ISSUE TITLE
Get errors

### ISSUE THREAD

**Issue by ValiaP** [healingbrew/HFSExtract#9]
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at HFSExtract.HFSArchive..ctor(Stream stream, String fileName) in G:\Datamining\Vindictus\HFSExtract2\HFSExtract\HFSArchive.cs:line 53
   at HFSExtract.CLI.Program.Main(String[] args) in G:\Datamining\Vindictus\HFSExtract2\HFSExtract.CLI\Program.cs:line 17

I am very new to this area. Thanks a lot if anyone could help!

**Comment by SakuraUO** [comment]
Don't know why you're getting that error. Works perfectly fine for me.

- Did you get the hotfix?
- You are sure your directories are set up properly?

When I make my ".bat" file, this is how I set it up...

@echo off
start HFSExtract.CLI.exe "C:\Nexon\Library\vindictus\appdata\en-US\hfs" "C:\Users\Sakura\Desktop\NA Output"


1.) Make sure your first directory is linked to your HFS folder.
2.) The second directory is just your output folder (name it however you want).

Then, after this, double click the bat file, and it should just do its thing until its done.
